name: Micks cool Action

on: [push]

jobs: 
  greeting:
      runs-on: ubuntu-latest

      steps:
        - name: Monkey business
          run: echo "ğŸ¦§ğŸ¦ğŸ’"

  log-checker: 
      runs-on: ubuntu-latest

      steps:
        - name: Checkout Code ğŸ‘€
          uses: actions/checkout@v3

        - name: Looking for logs ğŸ¦«
          run: |
              echo "ğŸ¦«ğŸ¦«ğŸ¦« sending the log inspectors"
              count=$(grep -ro 'console\.log' . | wc -l)
              echo "ğŸªµ Found $count occurrences of 'console.log'"

  build-deploy:
      runs-on: ubuntu-latest

      steps:
        - name: Chekcout Code ğŸ‘€
          uses: actions/checkout@v3

        - name: Setup Nodejs ğŸ¥—
          uses: actions/setup-node@v3
          with: 
            node-version: 22

        - name: Install Dependencies ğŸ“©
          run: npm ci #clean install (preferred for automated workflows)

        - name: BUILD ğŸ‘·âš’ï¸
          run: npm run build

