name: Micks cool Action

on: [push]

permissions:
  contents: read  
  pages: write  
  id-token: write 

jobs: 
  greeting:
      runs-on: ubuntu-latest

      steps:
        - name: Monkey business
          run: echo "ğŸ¦§ğŸ¦ğŸ’"

  log-checker: 
      runs-on: ubuntu-latest

      steps:
        - name: Checkout Code ğŸ‘€
          uses: actions/checkout@v3

        - name: Looking for logs ğŸ¦«
          run: |
              echo "ğŸ¦«ğŸ¦«ğŸ¦« sending the log inspectors"
              count=$(grep -ro 'console\.log' . | wc -l)
              echo "ğŸªµ Found $count occurrences of 'console.log'"

  build-deploy:
    # environment:
      # name: github-pages  
      # url: ${{ steps.deployment.outputs.page_url }} 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code ğŸ‘€
        uses: actions/checkout@v3

      - name: Setup Nodejs ğŸ¥—
        uses: actions/setup-node@v3
        with: 
          node-version: 22

      - name: Install Dependencies ğŸ“©
        run: npm i 

      - name: BUILD ğŸ‘·âš’ï¸
        run: npm run build

      - name: Init Pages ğŸ“ƒ
        uses: actions/configure-pages@v4
      
      - name: Upload Build to Pages ğŸ“¡
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Deploy Page ğŸ¦§
        id: deployment
        uses: actions/deploy-pages@v4

