name: Micks cool Action

on: [push]

jobs: 
  greeting:
      runs-on: ubuntu-latest

      steps:
        - name: Monkey business
          run: echo "ğŸ¦§ğŸ¦ğŸ’"

  log-checker: 
      runs-on: ubuntu-latest

      steps:
        - name: Checkout Code ğŸ‘€
          uses: actions/checkout@v3

        - name: Looking for logs ğŸ¦«
          run: grep -ro 'console.log'
